# Site settings
title: Bacon Hill Kitchen Window
email: andrewkrug@gmail.com
description: "This is the view from my kitchen window using a Raspberry Pi B+ and nothing more."
baseurl: ""
url: "http://baconhill.house"
twitter_username: andrewkrug
github_username:  andrewkrug

# Build settings
markdown: kramdown
permalink: pretty
